TableSoccer/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TableSoccer.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TableSoccer/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Core;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TableSoccer.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        /// <summary>
        /// All the registered players.
        /// </summary>
        public List<Player> Players => SoccerTableManager.Instance().Players();

        /// <summary>
        /// All the registered teams.
        /// </summary>
        public List<Team> Teams => SoccerTableManager.Instance().Teams();

        /// <summary>
        /// Initializes a new instance of the <see cref="IndexModel"/> class.
        /// </summary>
        /// <param name="logger">The logger.</param>
        public IndexModel(ILogger<IndexModel> logger) => _logger = logger;

        /// <summary>
        /// Called when [post player].
        /// </summary>
        /// <param name="playerName">Name of the player.</param>
        public void OnPostPlayer(string playerName)
        {
            if (string.IsNullOrEmpty(playerName)) return;
            if (Players.Any(x => x.Name == playerName))
            {
                _logger.Log(LogLevel.Warning, "Player creation skipped as name is not unique.");
                return;
            }

            SoccerTableManager.Instance().AddNewPlayer(playerName);
            return;
        }

        /// <summary>
        /// Called when [post player delete].
        /// </summary>
        /// <param name="id">The identifier.</param>
        public void OnPostPlayerDelete(string id)
        {
            SoccerTableManager.Instance().DeletePlayer(id);
        }

        /// <summary>
        /// Called when [post team].
        /// </summary>
        public void OnPostTeam()
        {
            var players = new string[]
                {
                    Request.Form["First Player"],
                    Request.Form["Second Player"],
                    Request.Form["Third Player"]
                }
                .Where(x => !string.IsNullOrEmpty(x))
                .Select(x => Players.FirstOrDefault(y => y.Name == x))
                .ToHashSet();
            
            if (players.Count == 0) return;
            
            if (TeamAlreadyExists(players))
            {
                _logger.Log(LogLevel.Warning, "Team creation skipped as a team with the same members already exists.");
                return;
            }

            SoccerTableManager.Instance().AddNewTeam(players, Request.Form["teamName"]);
        }

        /// <summary>
        /// Called when [post team delete].
        /// </summary>
        /// <param name="id">The identifier.</param>
        public void OnPostTeamDelete(string id)
        {
            SoccerTableManager.Instance().DeleteTeam(id);
        }

        private bool TeamAlreadyExists(IEnumerable<Player> players)
        {
            var sortedPlayers = players.Select(x => x.Name).OrderBy(x => x).ToList();
            return Teams.Any(x => x.Members.Select(y => y.Name).OrderBy(z => z).SequenceEqual(sortedPlayers));
        }
    }
}

TableSoccer/Pages/MatchMaker.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Core;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TableSoccer.Pages
{
    public class MatchMakerModel : PageModel
    {
        /// <summary>
        /// Gets the team list.
        /// </summary>
        public List<Team> Teams => SoccerTableManager.Instance().Teams();

        /// <summary>
        /// Gets the list of proposed matches.
        /// </summary>
        public List<Match> ProposedMatches { get; private set; } = null;

        /// <summary>
        /// Gets a value indicating whether this instance has proposed matches.
        /// </summary>
        public bool HasProposedMatches => ProposedMatches != null;

        /// <summary>
        /// Called when [post make matches].
        /// </summary>
        public void OnPostMakeMatches()
        {
            var selectedTeams = Teams
                .Where(x => Request.Form.ContainsKey(x.Id))
                .ToDictionary(team => team, team => SoccerTableManager.Instance().TeamStats(team));

            ProposedMatches = MatchMakerLogic.CreateBalancedMatches(selectedTeams);
        }
    }
}

TableSoccer/Pages/Matches.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Core;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TableSoccer.Pages
{
    public class MatchesModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        /// <summary>
        /// Gets the registered teams.
        /// </summary>
        public List<Team> Teams => SoccerTableManager.Instance().Teams();

        /// <summary>
        /// Gets the registered matches.
        /// </summary>
        public List<Match> Matches => SoccerTableManager.Instance().Matches();

        /// <summary>
        /// Initializes a new instance of the <see cref="MatchesModel"/> class.
        /// </summary>
        /// <param name="logger">The logger.</param>
        public MatchesModel(ILogger<IndexModel> logger) => _logger = logger;

        /// <summary>
        /// Called when [post match].
        /// </summary>
        public void OnPostMatch()
        {
            var homeTeam = Teams.Single(x => string.Equals(x.Name, Request.Form["Home Team"]));
            var visitorTeam = Teams.Single(x => string.Equals(x.Name, Request.Form["Visitor Team"]));
            var homeScore = int.Parse(Request.Form["homeScore"]);
            var visitorScore = int.Parse(Request.Form["visitorScore"]);
            var date = Convert.ToDateTime(Request.Form["matchDate"]);

            if (Equals(homeTeam, visitorTeam))
            {
                _logger.Log(LogLevel.Warning, "Match creation skipped because home and visitor are the same team.");
                return;
            }

            if (homeTeam.Members.Any(x => visitorTeam.Members.Contains(x))
                || visitorTeam.Members.Any(x => homeTeam.Members.Contains(x)))
            {
                _logger.Log(LogLevel.Warning, "Match creation skipped because one or more members is part of both teams.");
                return;
            }

            if (homeScore < 0 || visitorScore < 0)
            {
                _logger.Log(LogLevel.Warning, "Match creation skipped because of invalid score (must be greater than 0).");
                return;
            }

            SoccerTableManager.Instance().AddMatch(homeTeam, visitorTeam, homeScore, visitorScore, date);
        }

        /// <summary>
        /// Called when [post match delete].
        /// </summary>
        /// <param name="id">The identifier.</param>
        public void OnPostMatchDelete(string id)
        {
            SoccerTableManager.Instance().DeleteMatch(id);
        }
    }
}

TableSoccer/Pages/Statistics.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Core;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TableSoccer.Pages
{
    public class StatisticsModel : PageModel
    {
        /// <summary>
        /// Gets a value indicating whether there are registered matches.
        /// </summary>
        public bool HasMatches { get; private set; }

        /// <summary>
        /// Gets a value indicating whether there are registered matches this week.
        /// </summary>
        public bool HasMatchesThisWeek { get; private set; }

        /// <summary>
        /// Gets the list of all teams.
        /// </summary>
        public IEnumerable<Team> Teams => SoccerTableManager.Instance().Teams();

        /// <summary>
        /// Gets the dates of the current week.
        /// </summary>
        public string CurrentWeekDates
        {
            get
            {
                var (weekBeginning, weekEnding) = SoccerTableManager.Instance().GetCurrentWeek();
                return $"{weekBeginning:dd/MM} - {weekEnding:dd/MM}";
            }
        }

        /// <summary>
        /// Gets the general ranking.
        /// </summary>
        public List<(Team team, int points, int matches)> Ranking() => 
            SoccerTableManager.Instance().Ranking();

        /// <summary>
        /// Gets the current week ranking.
        /// </summary>
        public List<(Team team, int points, int matches)> CurrentWeekRanking() => 
            SoccerTableManager.Instance().CurrentWeekRanking();

        /// <summary>
        /// Gets the general overalls stats for all teams.
        /// </summary>
        public TeamStats OverallStats() => SoccerTableManager.Instance().OverallStats();

        /// <summary>
        /// Gets the general current week stats.
        /// </summary>
        public TeamStats CurrentWeekStats() => SoccerTableManager.Instance().CurrentWeekStats();

        private static string DateToString(DateTime d) => $"\"{d:dd MMM}\"";

        /// <summary>
        /// Gets the overall progress dates (used as labels for the chart).
        /// </summary>
        public string OverallProgressDatesString { get; private set; }

        /// <summary>
        /// Gets the current week progress dates (used as labels for the chart).
        /// </summary>
        public string CurrentWeekProgressDatesString { get; private set; }

        /// <summary>
        /// Gets the data sets, relative to the whole period, for all teams.
        /// </summary>
        public string OverallDataSets() => 
            Teams.Aggregate("", (s, team) => s + CreateDataSet(team, true) + ", ")[..^2];

        /// <summary>
        /// Gets the data sets, relative to the current week, for all teams.
        /// </summary>
        public string CurrentWeekDataSets()
        {
            return Teams.Aggregate("", (s, team) => s + CreateDataSet(team, false) + ", ")[..^2];
        }

        private static string CreateDataSet(Team team, bool overall)
        {
            var (r, g, b) = RandomColor();

            return @"{
            label: '" + team.Name + @"',
            borderWidth: 2,
            data: [" + GetProgressesForTeam(team, overall) + @"],
            borderColor:'rgba(" + r + "," + g + "," + b + @", 1)',
            backgroundColor:'rgba(" + r + "," + g + "," + b + @", 0.05)'
            }";
        }

        private static string GetProgressesForTeam(Team team, bool overall)
        {
            var progresses = overall
                ? SoccerTableManager.Instance().DailyProgress(team)
                : SoccerTableManager.Instance().CurrentWeekProgress(team);

            return progresses
                .Select(x => x.points)
                .Aggregate("", (s, points) => s + points + ", ")[..^2];
        }

        private static (int r, int g, int b) RandomColor()
        {
            var r = new Random();
            return (120, r.Next(175, 210), r.Next(256));
        }

        /// <summary>
        /// Called when [get].
        /// </summary>
        public void OnGet()
        {
            var matches = SoccerTableManager.Instance().Matches();
            HasMatches = matches.Count > 0;
            if (!HasMatches) return;

            var dates = matches.Select(x => x.Date).ToHashSet().OrderBy(x => x).ToList();
            OverallProgressDatesString = dates.Aggregate("", (s, date) => s + DateToString(date) + ", ")[..^2];

            var (weekBeginning, weekEnding) = SoccerTableManager.Instance().GetCurrentWeek();
            var currentWeekDates = matches.Select(x => x.Date)
                .Where(x => x >= weekBeginning && x <= weekEnding).ToHashSet().OrderBy(x => x).ToList();

            HasMatchesThisWeek = currentWeekDates.Count > 0;
            if (!HasMatchesThisWeek) return;

            CurrentWeekProgressDatesString = currentWeekDates.Aggregate("", (s, date) => s + DateToString(date) + ", ")[..^2];
        }
    }
}

TableSoccer/Pages/TeamStats.cshtml.cs
using System;
using System.Linq;
using Core;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TableSoccer.Pages
{
    public class TeamStatsModel : PageModel
    {
        private (DateTime date, int points)[] _dailyProgress;
        private (DateTime date, int points)[] _currentWeekProgress;

        /// <summary>
        /// Gets a value indicating whether this team has statistics.
        /// </summary>
        public bool HasStats => SoccerTableManager.Instance().TeamHasStats(Team);

        /// <summary>
        /// Gets a value indicating whether this team has statistics relative to the current week.
        /// </summary>
        public bool HasCurrentWeekStatistics => SoccerTableManager.Instance().TeamHasStatsForCurrentWeek(Team);

        /// <summary>
        /// Gets the team.
        /// </summary>
        public Team Team { get; private set; }

        /// <summary>
        /// Gets the team statistics.
        /// </summary>
        public TeamStats TeamStatistics => SoccerTableManager.Instance().TeamStats(Team);

        /// <summary>
        /// Gets the team statistics relative to the current week.
        /// </summary>
        public TeamStats CurrentWeekTeamStatistics => SoccerTableManager.Instance().CurrentWeekTeamStats(Team);

        /// <summary>
        /// Gets the current week dates in string format.
        /// </summary>
        public string CurrentWeekDates
        {
            get
            {
                var (weekBeginning, weekEnding) = SoccerTableManager.Instance().GetCurrentWeek();
                return $"{weekBeginning:dd/MM} - {weekEnding:dd/MM}";
            }
        }

        /// <summary>
        /// Values for the X axis of the overall progresses chart.
        /// </summary>
        public string ProgressDatesString() =>
            _dailyProgress.Select(x => x.date).Aggregate("", (s, date) => s + DateToString(date) + ", ")[..^2];

        /// <summary>
        /// Values for the Y axis of the overall progresses chart.
        /// </summary>
        public string ProgressPointsString() =>
            _dailyProgress.Select(x => x.points).Aggregate("", (s, points) => s + points + ", ")[..^2];

        /// <summary>
        /// Values for the X axis of the current week progresses chart.
        /// </summary>
        public string CurrentWeekProgressDatesString() =>
            _currentWeekProgress.Select(x => x.date).Aggregate("", (s, date) => s + DateToString(date) + ", ")[..^2];

        /// <summary>
        /// Values for the Y axis of the current week progresses chart.
        /// </summary>
        public string CurrentWeekProgressPointsString() =>
            _currentWeekProgress.Select(x => x.points).Aggregate("", (s, points) => s + points + ", ")[..^2];

        private static string DateToString(DateTime d) => $"\"{d:dd MMM}\"";

        /// <summary>
        /// Called when [get].
        /// </summary>
        public void OnGet()
        {
            if (!Request.Query.ContainsKey("id")) return;

            Team = SoccerTableManager.Instance().Teams().FirstOrDefault(x => x.Id == Request.Query["id"].ToString());
            if (Team == null) return;

            if (SoccerTableManager.Instance().TeamHasStats(Team))
                _dailyProgress = SoccerTableManager.Instance().DailyProgress(Team);
            
            if (SoccerTableManager.Instance().TeamHasStatsForCurrentWeek(Team))
                _currentWeekProgress = SoccerTableManager.Instance().CurrentWeekProgress(Team);
        }
    }
}

TableSoccer/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Table Soccer Participants</h1>
</div>

<div class="main">
    <div class="tableContainer">

        <div class="table">
            <form action="" method="post">
                <h3>Players:</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th> Name </th>
                        <th> Actions </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var player in Model.Players)
                    {
                        <tr>
                            <td>
                                @player.Name
                            </td>
                            <td>

                                <input type="submit" asp-page-handler="playerDelete" asp-route-id="@player.Id" value=" Delete ">
                            </td>
                        </tr>
                    }
                    <tr>
                        <td>
                            <input id="playerNameInput" type="text" name="playerName" placeholder="Player name"/>
                        </td>
                        <td>
                            <input id="addPlayerBt" type="submit" asp-page-handler="player" value=" Add " disabled="disabled">
                            @{
                                // disabling/enabling Add button depending on the completion of the name field
                                <script type="text/javascript">
                                    var newPlayerName = document.getElementById('playerNameInput');
                                    var addPlayerButton = document.getElementById('addPlayerBt');

                                    function checkForDefaultAndSetButton() {
                                        var enabled = newPlayerName.value !== '';
                                        addPlayerButton.disabled = !enabled;
                                    }

                                    newPlayerName.addEventListener("input", checkForDefaultAndSetButton);
                                </script>
                            }
                        </td>
                    </tr>
                    </tbody>
                </table>
            </form>
        </div>

        <div class="table">
            <form action="" method="post">
                <h3>Teams:</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th> Name </th>
                        <th> Actions </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var team in Model.Teams)
                    {
                        <tr>
                            <td>
                                @{
                                    var displayName = team.Name;
                                    if (displayName != team.MemberNames)
                                    {
                                        displayName += $" ({team.MemberNames})";
                                    }
                                }
                                @displayName
                            </td>
                            <td>
                                <input type="submit" asp-page-handler="teamDelete" asp-route-id="@team.Id" value=" Delete ">
                            </td>
                        </tr>
                    }
                    <tr>
                        <td>
                            <input type="text" name="teamName" placeholder="Team name (optional)"/>
                        </td>
                        <td>
                            @Html.DropDownList("First player", new SelectList(Model.Players), "Select A Player", new {@id = "firstDD"})
                            @Html.DropDownList("Second player", new SelectList(Model.Players), "Select A Player", new {@id = "secondDD"})
                            @Html.DropDownList("Third player", new SelectList(Model.Players), "Select A Player", new {@id = "thirdDD"})
                        </td>
                        <td>
                            <input type="submit" id="addTeamBt" asp-page-handler="team" value=" Add " disabled="disabled">
                            @{
                                // disabling/enabling Add button depending on the DropDown current selection
                                <script type="text/javascript">
                                    var firstDD = document.getElementById('firstDD');
                                    var secondDD = document.getElementById('secondDD');
                                    var thirdDD = document.getElementById('thirdDD');
                                    var addTeamButton = document.getElementById('addTeamBt');

                                    function notDefault(dropDown) { return dropDown.value !== ''; }

                                    function checkForDefaultAndSetButton() {
                                        var enabled = notDefault(firstDD) ||
                                            notDefault(secondDD) ||
                                            notDefault(thirdDD);
                                        addTeamButton.disabled = !enabled;
                                    }

                                    firstDD.addEventListener("change", checkForDefaultAndSetButton);
                                    secondDD.addEventListener("change", checkForDefaultAndSetButton);
                                    thirdDD.addEventListener("change", checkForDefaultAndSetButton);
                                </script>
                            }
                        </td>
                    </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>

TableSoccer/Pages/MatchMaker.cshtml
@page
@model TableSoccer.Pages.MatchMakerModel
@{
    ViewData["Title"] = "Match Maker";
}
<style type="text/css">
    .matchMakerBt {
        margin: 150px;
        width: 100px;
        height: 60px
    }

    .instruction { margin-bottom: 30px; margin-top: 30px }
</style>

<div class="text-center">
    <h1 class="display-4">Match Maker</h1>
</div>

<script>
    function DisableStartButtonIfNoCheckboxIsEnabled() {
        var count = 0;
        var checkboxes = document.querySelectorAll("input[type='checkbox']");
        for (var i = 0; i < checkboxes.length; i++)
            if (checkboxes[i].checked)
                count++;

        document.getElementById("matchMakerBt").disabled = count < 2;
    }
</script>

<div class="main">

    <div class="instruction">The Match Maker is a <b>state-of-the-art tool</b> that, using ultra sophisticated calculations, can combine teams in balanced matches.</div>

    <form action="" method="post">

        <div class="tableContainer">

            <div class="table">
                <h3>Teams:</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th> Name </th>
                            <th> Include </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var team in Model.Teams)
                        {
                            <tr>
                                <td>
                                    @{
                                        var displayName = team.Name;
                                        if (displayName != team.MemberNames)
                                        {
                                            displayName += $" ({team.MemberNames})";
                                        }
                                    }
                                    @displayName
                                </td>
                                <td>
                                    @{
                                        var checkboxId = "cb" + team.Name.Replace(' ', '_');
                                        var checkboxName = team.Id;
                                    }
                                    <input tag="teamCheckbox" type="checkbox" id="@checkboxId" name="@checkboxName" checked="checked">
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="text-center">
                <input type="submit" asp-page-handler="MakeMatches" class="matchMakerBt" id="matchMakerBt" value=" START ">
                <script>
                    var checkboxes = document.querySelectorAll("input[type='checkbox']");
                    for (var i = 0; i < checkboxes.length; i++) {
                        checkboxes[i].addEventListener("change", DisableStartButtonIfNoCheckboxIsEnabled);
                    }
                </script>
            </div>
        </div>

        @if (Model.HasProposedMatches)
        {
            <div class="instruction">The following are the most balanced matches between the given teams.</div>
            
            <h3>Proposed Matches:</h3>

            <table class="table">
                <thead>
                    <tr>
                        <th> Home Team </th>
                        <th> Visitor Team </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var match in Model.ProposedMatches)
                    {
                        <tr>
                            <td> @match.HomeTeam.Name </td>
                            <td> @match.VisitorTeam.Name </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </form>
</div>

TableSoccer/Pages/Matches.cshtml
@page
@model TableSoccer.Pages.MatchesModel
@{
    ViewData["Title"] = "Matches";
}

<div class="text-center">
    <h1 class="display-4">Played Matches</h1>
</div>

<div class="main">
    <div class="table">
        <form action="" method="post">
            <table class="table">
                <thead>
                <tr>
                    <th> Home Team </th>
                    <th> Visitor Team </th>
                    <th> Result </th>
                    <th> Date </th>
                </tr>
                </thead>
                <tbody>
                @foreach (var match in Model.Matches)
                {
                    <tr>
                        <td> @match.HomeTeam.Name </td>
                        <td> @match.VisitorTeam.Name </td>
                        <td> @match.HomeScore - @match.VisitorScore</td>
                        <td> @match.Date.ToString("dd/MM/yyyy")</td>
                        <td>
                            <input type="submit" asp-page-handler="matchDelete" asp-route-id="@match.Id" value=" Delete ">
                        </td>
                    </tr>
                }
                <tr>
                    <td> @Html.DropDownList("Home team", new SelectList(Model.Teams), "Home Team", new {@id = "homeTeamDD"}) </td>
                    <td> @Html.DropDownList("Visitor team", new SelectList(Model.Teams), "Visitor Team", new {@id = "visitorsDD"}) </td>
                    <td>
                        <input type="number" class="scoreInput" name="homeScore" placeholder="Home Score" value="0"/> -
                        <input type="number" class="scoreInput" name="visitorScore" placeholder="Visitor Score" value="0"/>
                    </td>
                    <td>
                        <input type="date" name="matchDate" value="@DateTime.Today.ToString("yyyy-MM-dd")"/>
                    </td>
                    <td>
                        <input id="addMatchButton" type="submit" asp-page-handler="match" value=" Add " disabled="disabled">
                        @{
                            // disabling/enabling Add button depending on the DropDown current selection
                            <script type="text/javascript">
                                var homeDD = document.getElementById('homeTeamDD');
                                var visitorDD = document.getElementById('visitorsDD');
                                var addMatchButton = document.getElementById('addMatchButton');

                                function notDefault(dropDown) {
                                    return dropDown.value !== '';
                                }

                                function checkForDefaultAndSetButton() {
                                    var enabled = notDefault(homeDD) && notDefault(visitorDD);
                                    addMatchButton.disabled = !enabled;
                                }

                                homeDD.addEventListener("change", checkForDefaultAndSetButton);
                                visitorDD.addEventListener("change", checkForDefaultAndSetButton);
                            </script>
                        }
                    </td>
                </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>